# =============================================================================
# Project      : eToolManager
# File         : etoolmanager/reports/generator.py
# Purpose      : Generate JSON and Markdown environment reports.
#
# Author       : Tejas Kamble
# Email        : tejasksocials@gmail.com
# Phone        : +91 8928545352
# Portfolio    : https://tejas-personal-portfolio-dev.vercel.app/
# LinkedIn     : https://www.linkedin.com/in/tejas-kamble-5342443b1
# GitHub       : https://github.com/tejasworkspacews1-ui
#
# Repository   : https://github.com/tejasworkspacews1-ui/etoolmanager
# Created      : 2026
#
# Developed by Tejas Kamble as a submission prototype for the
# FOSSEE eSim Semester Long Internship - Autumn 2026
# (Task 5: Automated Tool Manager).
# =============================================================================

"""Report serialisation for dependency scans and tool status.

The generators in this module take a :class:`DependencyReport` (and
optionally a list of tool statuses) and write them to disk as either
structured JSON or human-readable Markdown.  Both formats include:
system information, installed tools, missing dependencies, suggested
fixes, and a timestamp.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from etoolmanager.core.tool_manager import ToolStatus
from etoolmanager.dependency.scanner import DependencyReport
from etoolmanager.utils.logger import get_logger

logger = get_logger(__name__)


def _build_payload(
    report: DependencyReport, tool_statuses: list[ToolStatus] | None
) -> dict[str, Any]:
    """Combine a dependency report and tool statuses into one dictionary.

    Args:
        report: Dependency scan result.
        tool_statuses: Optional list of per-tool status snapshots.

    Returns:
        dict[str, Any]: Flat payload ready for JSON serialisation.
    """
    payload = report.to_dict()

    if tool_statuses:
        payload["tools"] = [status.to_dict() for status in tool_statuses]

    payload["author"] = {
        "name": "Tejas Kamble",
        "email": "tejasksocials@gmail.com",
        "github": "https://github.com/tejasworkspacews1-ui",
        "statement": (
            "Report generated by eToolManager, developed by Tejas Kamble as a "
            "submission prototype for the FOSSEE eSim Semester Long Internship "
            "- Autumn 2026 (Task 5: Automated Tool Manager)."
        ),
    }
    return payload


def generate_json_report(
    report: DependencyReport,
    output_path: Path,
    tool_statuses: list[ToolStatus] | None = None,
) -> Path:
    """Write the report as a pretty-printed JSON file.

    Args:
        report: Dependency scan result.
        output_path: Destination file (``reports/report.json``).
        tool_statuses: Optional per-tool status snapshots.

    Returns:
        Path: The path the report was written to.
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)
    payload = _build_payload(report, tool_statuses)

    output_path.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    logger.info("JSON report written to %s", output_path)
    return output_path


def generate_markdown_report(
    report: DependencyReport,
    output_path: Path,
    tool_statuses: list[ToolStatus] | None = None,
) -> Path:
    """Write the report as a formatted Markdown document.

    Args:
        report: Dependency scan result.
        output_path: Destination file (``reports/report.md``).
        tool_statuses: Optional per-tool status snapshots.

    Returns:
        Path: The path the report was written to.
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)
    lines: list[str] = []

    lines.append("# eToolManager - Environment Readiness Report")
    lines.append("")
    lines.append(f"**Timestamp:** {report.timestamp}")
    lines.append("")
    lines.append("## System Information")
    lines.append("")
    lines.append(f"- **OS:** {report.system.os_display} (`{report.system.os_name}`)")
    lines.append(f"- **Version:** {report.system.version}")
    lines.append(f"- **Architecture:** {report.system.architecture}")
    lines.append(f"- **Package Manager:** {report.system.package_manager}")
    lines.append(f"- **Python:** {report.system.python_version}")
    lines.append("")

    lines.append("## Summary")
    lines.append("")
    lines.append(
        f"- **Ready:** {'&#9989; Yes' if report.ready else '&#10060; No'}"
    )
    lines.append(
        f"- **Checks Passed:** {report.passed_count} / "
        f"{report.passed_count + report.failed_count}"
    )
    lines.append(f"- **Checks Failed:** {report.failed_count}")
    lines.append("")

    if tool_statuses:
        lines.append("## Installed Tools")
        lines.append("")
        lines.append("| Tool | Installed | Version | Minimum | Meets Minimum |")
        lines.append("|------|-----------|---------|---------|---------------|")
        for status in tool_statuses:
            lines.append(
                f"| {status.name} | {'Yes' if status.installed else 'No'} | "
                f"{status.version or 'N/A'} | "
                f"{status.minimum_version or 'N/A'} | "
                f"{'Yes' if status.meets_minimum else 'No'} |"
            )
        lines.append("")

    lines.append("## Dependency Checks")
    lines.append("")
    lines.append("| Category | Dependency | Status | Detail |")
    lines.append("|----------|------------|--------|--------|")
    for check in report.checks:
        status_text = "&#9989;" if check.ok else "&#10060;"
        lines.append(
            f"| {check.category} | {check.name} | {status_text} | {check.detail} |"
        )
    lines.append("")

    lines.append("## Missing Dependencies")
    lines.append("")
    if report.missing:
        for check in report.missing:
            lines.append(f"- **{check.name}** ({check.category}): {check.detail}")
        lines.append("")
    else:
        lines.append("_No missing dependencies detected._")
        lines.append("")

    lines.append("## Suggested Fixes")
    lines.append("")
    if report.fixes:
        for idx, fix in enumerate(report.fixes, start=1):
            lines.append(f"{idx}. {fix}")
        lines.append("")
    else:
        lines.append("_No fixes needed - environment is ready._")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("## Author & Attribution")
    lines.append("")
    lines.append(
        "This report was generated by **eToolManager**, designed and implemented by "
    )
    lines.append("")
    lines.append("| Field | Value |")
    lines.append("|-------|-------|")
    lines.append("| **Author** | Tejas Kamble |")
    lines.append("| **Email** | [tejasksocials@gmail.com](mailto:tejasksocials@gmail.com) |")
    lines.append("| **Phone** | +91 8928545352 |")
    lines.append("| **Portfolio** | https://tejas-personal-portfolio-dev.vercel.app/ |")
    lines.append("| **LinkedIn** | https://www.linkedin.com/in/tejas-kamble-5342443b1 |")
    lines.append("| **GitHub** | https://github.com/tejasworkspacews1-ui |")
    lines.append("")
    lines.append(
        "Developed by Tejas Kamble as a submission prototype for the "
        "FOSSEE eSim Semester Long Internship - Autumn 2026 (Task 5: Automated Tool Manager)."
    )
    lines.append("")

    output_path.write_text("\n".join(lines), encoding="utf-8")
    logger.info("Markdown report written to %s", output_path)
    return output_path